### ISSUE TITLE
Performance-hit in PS4 games with kstuff

### ISSUE THREAD

**Issue by ChaozzZJohnny** [sleirsgoevy/ps4jb-payloads#20]
Don't know if this is the right channel for this, but I thought, I'd share my findings.
I tried around a lot with Bloodborne and made some FPS-measurements using kstuff and libhijacker (or the framerate patch by Lance on its own). It seems like kstuff has a bigger impact on framerate which relates to CPU- and Memory-heavy tasks like loading assets.

I could bring Bloodborne down to 55 or even 50 fps pretty regularly when traversing the game and it doesn't happen when playing the disc version of the game with BD-J and libhijacker, there it is stable 60 fps all the way down. So it seems to me that kstuff brings down performance quite a bit in some scenarios.

Here is a video of my testing on a 4.50 PS5:
https://www.youtube.com/watch?v=HUnJxmQzHRE

I also tried the game on a fresh 4.03 PS5 that is pretty much stock and with different combinations of kstuff and libhijacker (or the patch by Lance). Bloodborne behaved the same during all runs.

Hope this is of any use to you. Keep up the great work, Sleir!

**Comment by sleirsgoevy** [comment]
Created a dedicated issue #22 for this kind of reports.

**Comment by ceedveed** [comment]
> Don't know if this is the right channel for this, but I thought, I'd share my findings. I tried around a lot with Bloodborne and made some FPS-measurements using kstuff and libhijacker (or the framerate patch by Lance on its own). It seems like kstuff has a bigger impact on framerate which relates to CPU- and Memory-heavy tasks like loading assets.
> 
> I could bring Bloodborne down to 55 or even 50 fps pretty regularly when traversing the game and it doesn't happen when playing the disc version of the game with BD-J and libhijacker, there it is stable 60 fps all the way down. So it seems to me that kstuff brings down performance quite a bit in some scenarios.
> 
> Here is a video of my testing on a 4.50 PS5: https://www.youtube.com/watch?v=HUnJxmQzHRE
> 
> I also tried the game on a fresh 4.03 PS5 that is pretty much stock and with different combinations of kstuff and libhijacker (or the patch by Lance). Bloodborne behaved the same during all runs.
> 
> Hope this is of any use to you. Keep up the great work, Sleir!

Just wondering if this was ever solved with later versions of etaHEN/kstuff? I experience the same with bloodborne.
